In [1]:
import os
import cv2
import numpy as np
import torch # The top-level PyTorch package and tensor library.
import torch.nn as nn # A subpackage that contains modules and extensible classes for building neural networks.
import torch.optim as optim # A subpackage that contains standard optimization operations like SGD and Adam.
import torch.nn.functional as F # functional interface that contains typical operations used for building neural networks like loss functions and convolutions.

import torchvision # package that provides access to popular datasets, model architectures, and image transformations for computer vision.
import torchvision.transforms as transforms # An interface that contains common transforms for image processing.

torch.set_printoptions(linewidth=120) # to print in one line
torch.set_grad_enabled(True)#to update new gradients have to have past gradients so make pytorch to trach the grad values

from torch.autograd import Variable
from torch.utils.data import DataLoader
from PIL import Image

In [2]:
def check_pixel(pixel):
    first = 0
    second = 0
    third = 0
    
    for i in range(70, 256):
        if (pixel[0] == i):
            first = 1
            
    for j in range(70, 256):
        if (pixel[0] == j):
            second = 1
            
    for k in range(70, 256):
        if (pixel[0] == k):
            third = 1
                    
    return (first & second & third)

In [3]:
def create_before_cut(img1, img2, img3, img4):

    height = img1.shape[0]
    width = img1.shape[1]
    
    create_before_cut = np.zeros((height, width, 3), np.uint8)
    
    for i in range(0, height):
        for j in range(0, width):

            if not(check_pixel(img1[i, j])) :
                pixel = img1[i, j]

            elif not(check_pixel(img2[i, j])) :
                pixel = img2[i, j]    

            elif not(check_pixel(img3[i, j])) :
                pixel = img3[i, j] 

            elif not(check_pixel(img4[i, j])) :
                pixel = img4[i, j]     

            else:
                pixel = img1[i, j]

            create_before_cut[i, j] = pixel 
            
    cv2.imwrite('create_before_cut.png',create_before_cut)        
    return(create_before_cut)

In [4]:
def create_after_cut(img5, img6, img7, img8, img9, img10, img11, img12):

    height = img6.shape[0]
    width = img6.shape[1]

    create_after_cut = np.zeros((height, width, 3), np.uint8)
    
    for i in range(0, height):
        for j in range(0, width):

            if not(check_pixel(img6[i, j])) :
                pixel = img6[i, j]

            elif not(check_pixel(img5[i, j])) :
                pixel = img5[i, j]    

            elif not(check_pixel(img7[i, j])) :
                pixel = img7[i, j] 

            elif not(check_pixel(img8[i, j])) :
                pixel = img8[i, j]  

            elif not(check_pixel(img9[i, j])) :
                pixel = img9[i, j]

            elif not(check_pixel(img10[i, j])) :
                pixel = img10[i, j]

            elif not(check_pixel(img11[i, j])) :
                pixel = img11[i, j] 

            elif not(check_pixel(img12[i, j])) :
                pixel = img12[i, j] 

            else:
                pixel = img6[i, j]

            create_after_cut[i, j] = pixel  

    cv2.imwrite('create_after_cut.png',create_after_cut)  
    return(create_after_cut)

In [5]:
img1 = cv2.imread('1.png')
img2 = cv2.imread('2.png')
img3 = cv2.imread('3.png')
img4 = cv2.imread('4.png')
img5 = cv2.imread('5.png')
img6 = cv2.imread('6.png')
img7 = cv2.imread('7.png')
img8 = cv2.imread('8.png')
img9 = cv2.imread('9.png')
img10 = cv2.imread('10.png')
img11 = cv2.imread('11.png')
img12 = cv2.imread('12.png')

create_before_cut = create_before_cut(img1, img2, img3, img4)
create_after_cut = create_after_cut(img5, img6, img7, img8, img9, img10, img11, img12)

cv2.imshow('recreated image before cutting', create_before_cut)
cv2.imshow('recreated image after cutting', create_after_cut)

cv2.waitKey(0)
cv2.destroyAllWindows()    

'    \n        elif not(check_pixel(img5[i, j])) :\n            pixel = img5[i, j]\n            \n        elif not(check_pixel(img6[i, j])) :\n            pixel = img6[i, j]\n            \n        elif not(check_pixel(img7[i, j])) :\n            pixe1 = img7[i, j] \n            \n        elif not(check_pixel(img8[i, j])) :\n            pixe1 = img8[i, j]  \n            \n        elif not(check_pixel(img9[i, j])) :\n            pixel = img9[i, j]\n            \n        elif not(check_pixel(img10[i, j])) :\n            pixel = img10[i, j]\n            \n        elif not(check_pixel(img11[i, j])) :\n            pixe1 = img11[i, j] \n            \n        elif not(check_pixel(img12[i, j])) :\n            pixe1 = img12[i, j]     \n        '

In [105]:
cv2.imshow('recreated image', img6)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [181]:
image = np.zeros((300, 300, 3), np.uint8)
# Fill image with red color(set each pixel to red)
image[:] = (30, 80, 120) # B G R

cv2.imshow('recreated image', image)

cv2.waitKey(0)#press any key to escape
cv2.destroyAllWindows()

In [ ]:
[255 255 243]
[255 255 235]
[255 255 238]                          255   255   225
[255 255 237]
[255 255 235]
[253 255 236]
[249 253 227]
[255 248 203]
[255 243 214]
[229 240 215]
[254 255 242]

In [20]:
i = 99
j = 99
k = 0
img1 = cv2.imread('1.png')
img1[0 ,0] = [i, j, k]

print(img1[0, 0][2])
"""
if not(((img1[i, j] > [100,200,200]).all()) and ((img1[i, j] <= [255,255,255]).all())) :
    print("not in the range")
    
else:
    print("in the range")
""" 

0


'\nif not(((img1[i, j] > [100,200,200]).all()) and ((img1[i, j] <= [255,255,255]).all())) :\n    print("not in the range")\n    \nelse:\n    print("in the range")\n'

In [47]:
def check_pixel(pixel):
    print(pixel)
    first = 0
    second = 0
    third = 0
    
    for i in range(245, 256):
        if (pixel[0] == i):
            first = 1
            
    for j in range(245, 256):
        if (pixel[0] == j):
            second = 1
            
    for k in range(245, 256):
        if (pixel[0] == k):
            third = 1
                    
    return (first & second & third)

In [51]:
i = 100
j = 255
k = 255

img1 = cv2.imread('1.png')
img1[0 ,0] = [i, j, k]
print(check_pixel(img1[0 ,0]))

[100 255 255]
0
